name: Deploy to Firebase Hosting | Prod
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Firebase Hosting | Prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build
        run: npm ci && npm run build-prod

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SKYCAST_21230 }}'
          channelId: live
          projectId: skycast-21230
